spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:~/kakao/pay/membership/h2-console;
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8080

logging:
  level:
    com.kakaopay.mbs: DEBUG
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        SQL: DEBUG